theme: jekyll-theme-architect
title: "Best Fast Food Places"
description: "Ryan H, Lucas M, Shivansh G, Haoxuan blog"
gitorg: "https://github.com/RyanHaki/frontendproject"
description: "Rating's on your favorite fast foods."
google_analytics:
